In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("data/hospital_readmissions.csv")
df.replace("Missing",np.nan,inplace=True)
numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_columns = [feature for feature in df.columns if df[feature].dtype == 'O']
print(numeric_features,categorical_columns)

['time_in_hospital', 'n_lab_procedures', 'n_procedures', 'n_medications', 'n_outpatient', 'n_inpatient', 'n_emergency'] ['age', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'glucose_test', 'A1Ctest', 'change', 'diabetes_med', 'readmitted']


In [4]:
import pandas as pd

data = {'col1': 10, 'col2': 'abc'}
df = pd.DataFrame(data,index=[0])
print(df)

   col1 col2
0    10  abc


In [8]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(encoded_missing_value=-1.)
train_df=encoder.fit_transform(df)
df.head()
columns=df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   age                25000 non-null  object
 1   time_in_hospital   25000 non-null  int64 
 2   n_lab_procedures   25000 non-null  int64 
 3   n_procedures       25000 non-null  int64 
 4   n_medications      25000 non-null  int64 
 5   n_outpatient       25000 non-null  int64 
 6   n_inpatient        25000 non-null  int64 
 7   n_emergency        25000 non-null  int64 
 8   medical_specialty  12618 non-null  object
 9   diag_1             24996 non-null  object
 10  diag_2             24958 non-null  object
 11  diag_3             24804 non-null  object
 12  glucose_test       25000 non-null  object
 13  A1Ctest            25000 non-null  object
 14  change             25000 non-null  object
 15  diabetes_med       25000 non-null  object
 16  readmitted         25000 non-null  objec

In [7]:
for i in columns:
    print(i,":",df[i].unique())

age : ['[70-80)' '[50-60)' '[60-70)' '[40-50)' '[80-90)' '[90-100)']
time_in_hospital : [ 8  3  5  2  1  4  7 10  6 12 11  9 14 13]
n_lab_procedures : [ 72  34  45  36  42  51  44  19  67  37  35  69  60  73  52   9  16  62
  54  58  40  23  32  65   1  47  39  59  68  66  43  30  46  48   5  24
  70  25  29  49  53  94  18  61  11  33  28  83  50  71  86  38   3  41
  31  55  56  27  64  82  26  90  21   2  20  17  78 102  75  15   8   7
  76  63  57  10   4  22  91  74  14  13  89  79  81  84  80   6  77  12
 108  88  92  93 101  97 100  85  95  87  98  96  99 103 111 106 113 109
 105]
n_procedures : [1 2 0 6 3 5 4]
n_medications : [18 13 12  7 10 21 16  6 26 20 11 27 15  8 22 17 14 28  5 24  9 19  1 25
 32  3 31 23 39 34 40  4 38  2 33 56 44 29 46 30 47 41 35 36 50 49 54 57
 60 37 61 52 51 42 53 43 45 59 62 79 63 55 65 48 58 69 68 72 75 64]
n_outpatient : [ 2  0  1  3  7  5  4  6  9  8 11 10 15 21 13 12 27 16 14 33 20 18 23]
n_inpatient : [ 0  2  3  1  6  9  7  4  5  8 10 11 14 12 1

In [4]:
from sklearn.impute import KNNImputer


imputer=KNNImputer(n_neighbors=2,missing_values=-1.)
imputed_missing=imputer.fit_transform(train_df)
print(imputed_missing)

[[ 3.  7. 71. ...  0.  1.  0.]
 [ 3.  2. 33. ...  0.  1.  0.]
 [ 1.  4. 44. ...  1.  1.  1.]
 ...
 [ 3.  4. 11. ...  0.  0.  1.]
 [ 3.  1. 60. ...  1.  1.  0.]
 [ 1.  9. 36. ...  0.  0.  1.]]


In [ ]:
final_df=encoder.inverse_transform(imputed_missing)
print(age)
model2=OrdinalEncoder()

print(final_df[65])

['[70-80)', '[50-60)', '[60-70)', '[40-50)', '[80-90)', '[90-100)']
['[40-50)' 3 29 0 8 0 0 1 'InternalMedicine' 'Respiratory' 'Diabetes'
 'Digestive' 'no' 'no' 'yes' 'yes' 'yes']


In [7]:
df2=pd.DataFrame(final_df,columns=columns)
df2.head()
df2["age"]=model2.fit_transform(df2[["age"]])
print(df2.columns)
df2.to_csv(path_or_buf="hospital.csv")
df2.head()

Index(['age', 'time_in_hospital', 'n_lab_procedures', 'n_procedures',
       'n_medications', 'n_outpatient', 'n_inpatient', 'n_emergency',
       'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'glucose_test',
       'A1Ctest', 'change', 'diabetes_med', 'readmitted'],
      dtype='object')


age time_in_hospital n_lab_procedures  ... change diabetes_med readmitted
0  3.0                8               72  ...     no          yes         no
1  3.0                3               34  ...     no          yes         no
2  1.0                5               45  ...    yes          yes        yes
3  3.0                2               36  ...    yes          yes        yes
4  2.0                1               42  ...     no          yes         no

[5 rows x 17 columns]

In [8]:
df3=pd.DataFrame(imputed_missing,columns=columns)
df3.head()
df3.to_csv("hospital.csv")

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression, Ridge,Lasso
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X=df3.drop(columns="readmitted",axis=1)
Y=df3["readmitted"]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
models={
    'Logistic Regression Classification': LogisticRegression(),
'Decision Tree': DecisionTreeClassifier(),
'Random Forest': RandomForestClassifier(),
'Support Vector Machine': SVC(),
'Naive Bayes': MultinomialNB(),
'K-Nearest Neighbors': KNeighborsClassifier(),
"AdaBoost Regressor": AdaBoostClassifier()
}
report={}
for i in range(len(models)):
    model=list(models.values())[i]
    model.fit(X_train,Y_train)
    y_pred=model.predict(X_test)

    score=accuracy_score(Y_test,y_pred)

    report[list(models.keys())[i]]=score
print(report)

NameError: name 'train_df' is not defined

In [10]:
df["readmitted"].unique()
df['readmitted'].value_counts(normalize=True)

readmitted
no     0.52984
yes    0.47016
Name: proportion, dtype: float64